version: 1.0.{build}
skip_tags: true
environment:
  CURSETOKEN:
    secure: nGC9Ccwa4F7+jw/Fgd7MLwI41CJCx+ukQu7zmy0axA4muFndxX6xPUKZWJKl8HmY
cache: C:\Users\appveyor\.gradle\
build_script:
  - cmd: >-
      ./gradlew build --warning-mode=none
artifacts:
  - path: build\libs\*.jar
    name: GIRC-MOD
deploy:
  - provider: GitHub
    auth_token:
      secure: 5oeQuJ1HS/4OdMCprhYzOzLOFKUbiG0kDmYUTriCax28T9XKk0OS+M/CBc2FpJU5
    artifact: GIRC-MOD
    force_update: true
    on:
      branch: master
after_deploy:
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -match "master") {
        ./gradlew curseforge{{TEST}} -PcreateBuild
      }
